#!/bin/bash

pre_commit() {
    echo '+cargo fmt'
    cargo fmt --all
    # echo '+cargo test'
    # cargo test
    # echo '+cargo clippy -- -D warnings'
    # cargo clippy -- -D warnings
}


set -e

echo 'check user'
cd user
pre_commit
cd ..

echo 'check os'
cd os
pre_commit
cd ..

echo 'check vfs'
cd vfs
pre_commit
cd ..