[target.'cfg(target_os = "none")']
runner = "cargo run --package image_maker --"

[alias]
kbuild = "build --target x86_64-rustos-none.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-rustos-none.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-rustos-none.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
ktest = "test --target x86_64-rustos-none.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
ktestfile = "test --target x86_64-rustos-none.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem --package rustos --test "
