[target.'cfg(target_os = "none")']
runner = "cargo run --package image_maker --"

[alias]
kbuild = "build --target x86_64-rustos-none.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target x86_64-rustos-none.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --target x86_64-rustos-none.json -Zbuild-std=core -Zbuild-std-features=compiler-builtins-mem"
