[package]
name = "vfs"
version = "0.1.0"
edition = "2021"
readme = "Readmd.md"
keywords = ["vfs", "virtual", "filesystem"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
